---
- name: Determine latest GitHub release (local)
  delegate_to: localhost
  become: false
  uri:
    url: "https://api.github.com/repos/OSC/ondemand_exporter/releases/latest"
    body_format: json
  register: _github_release
  until: _github_release.status == 200
  run_once: true
  retries: 5

- name: Set ondemand_exporter_version
  set_fact:
    ondemand_exporter_version: "{{ _github_release.json.tag_name
      | regex_replace('^v?([0-9\\.]+)$', '\\1') }}"

- name: Set ondemand_exporter_download_url
  set_fact:
    ondemand_exporter_download_url: "https://github.com/OSC/ondemand_exporter/releases/download/v{{ ondemand_exporter_version }}/ondemand_exporter-{{ ondemand_exporter_version }}.linux-{{ ondemand_exporter_arch }}.tar.gz"
