---
- name: Check current ondemand_exporter version.
  command: "{{ ondemand_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: ondemand_exporter_version_check

- name: Configure latest version
  include_tasks: config-version.yaml
  when: >
    ondemand_exporter_version is match("latest")
    or ondemand_exporter_version is not defined

- name: Download and unarchive ondemand_exporter into temporary location.
  unarchive:
    src: "{{ ondemand_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: 0755
  when: >
    ondemand_exporter_version_check.stdout is not defined
    or ondemand_exporter_version not in ondemand_exporter_version_check.stdout
  register: ondemand_exporter_download_check

- name: Move ondemand_exporter binary into place.
  copy:
    src: "/tmp/ondemand_exporter-{{ ondemand_exporter_version }}.linux-{{ ondemand_exporter_arch }}/ondemand_exporter"
    dest: "{{ ondemand_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart ondemand_exporter
  when: >
    ondemand_exporter_download_check is changed
    or ondemand_exporter_version_check.stdout | length == 0

- name: Create ondemand_exporter user.
  user:
    name: ondemand_exporter
    shell: /sbin/nologin
    state: present

- name: Copy the ondemand_exporter systemd unit file.
  template:
    src: ondemand_exporter.service.j2
    dest: /etc/systemd/system/ondemand_exporter.service
    mode: 0644
  register: ondemand_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart ondemand_exporter
  when: ondemand_exporter_service is changed

- name: Ensure ondemand_exporter is running and enabled at boot.
  service:
    name: ondemand_exporter
    state: "{{ ondemand_exporter_state }}"
    enabled: "{{ ondemand_exporter_enabled }}"

- name: Verify ondemand_exporter is responding to requests.
  uri:
    url: "http://{% if ondemand_exporter_host !='' %}{{ ondemand_exporter_host }}{% else %}localhost{% endif %}:{{ ondemand_exporter_port }}/"
    return_content: true
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"
